[package]
name = "hierarchical_pathfinding"
version = "0.5.1"
authors = ["mich101mich <mich101mich@gmail.com>"]
edition = "2021"
description = "Quickly approximate Paths on a Grid"
repository = "https://github.com/mich101mich/hierarchical_pathfinding"
readme = "readme.md"
license = "MIT"
keywords = ["pathfinding", "dijkstra", "a-star", "grid"]
categories = ["algorithms"]
exclude = [
    "/.github/*",
    "/.vscode/*",
    "/img/*",
    "/.gitignore",
]

[dependencies]
hashbrown = "0.17.0"
log = { version = "0.4.0", optional = true }   # Feature used for measuring internal timings. Recommended to leave this off unless working on improvements to hierarchical_pathfinding.
rayon = { version = "1.8.0", optional = true }  # don't set this directly, use feature `parallel` instead.
slotmap = "1.1.1"

[dev-dependencies]
criterion = "0.8.0"
env_logger = "0.11.0"
log = "0.4.0"
nanorand = "0.8.0"
pathfinding = "4.15.0"

[features]
default = ["parallel"]
parallel = ["rayon", "hashbrown/rayon"]

[[bench]]
name = "my_benchmark"
harness = false
